# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'build'
        Dockerfile: 'Dockerfile'
        tags: '$(tag)'
    - script: 'docker rm /tbelbekcom'
    - script: 'docker run -d -p 8096:80 --name tbelbekcom tbelbekcom'
