# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
    steps:
    - script: 'docker build -t tbelbekcom .'
      displayName: 'Build Image'  
    # - script: 'docker stop /tbelbekcom'
    #   displayName: 'Stop running container'  
    # - script: 'docker rm /tbelbekcom'
    #   displayName: 'Remove old container'  
    - script: 'docker run -d -p 8096:80 --name tbelbekcom tbelbekcom'
      displayName: 'Start new container'  
        
